function [C_b__a] = rpy2dcm(phi_ba, theta_ba, psi_ba)
% Takes roll pitch and yaw values in radians and returns a directional
% cosine matrix (DCM).  Note that the transpose is accounted for in the
% function.

Rx = [1,  0,        0; ...
      0,  cos(phi_ba), sin(phi_ba); ...
      0, -sin(phi_ba), cos(phi_ba)];
  
Ry = [cos(theta_ba), 0, -sin(theta_ba); ...
       0,          1,  0; ...
       sin(theta_ba), 0,  cos(theta_ba)];
   
Rz = [ cos(psi_ba), sin(psi_ba), 0; ...
      -sin(psi_ba), cos(psi_ba), 0; ...
       0,        0,        1];
   
C_b__a = (Rx * Ry * Rz)'; % Note the transpose is taken here!